#version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8.1.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: devio
      MYSQL_DATABASE: ms_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres13:
    container_name: postgres13
    image: postgres:13.22
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devio
      POSTGRES_DB: ms_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  ms-usuarios:
    container_name: ms-usuarios
    image: markcode79/usuarios:latest
    #image: usuarios:latest
    #build:
    #  context: ./
    #  dockerfile: ./ms-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./ms-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  ms-cursos:
    container_name: ms-cursos
    image: markcode79/cursos:latest
    #image: cursos:latest
    #build:
    #  context: ./
    #  dockerfile: ./ms-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./ms-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres13
      - ms-usuarios
    restart: always 
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  spring:

